### ISSUE TITLE
Find missing file link in playlist

### ISSUE THREAD

**Issue by FunctionDJ** [Xen-E/pcxx#1]
I've been looking for an alternative to [ListFix](http://listfix.sourceforge.net/) since... well basically since forever because it hasn't been updated since 2012, 3 years before i even started using it.

As far as i know it's the only software that allows users to easily fix broken music file links in playlist files.

It would be absolutely amazing if this software also had this feature.

For it to work, the user would need to add directories or volumes for the application to scan and keep in a database for looking up missing files.

Those missing files could, depending on a user-setting, be either searched by longest matching string (in case the parent directory was moved to a different drive for example, this would prioritize this file over a file with the same name with a different parent directory name) or using fuzzy string search.

What do you think of this feature? Is it outside the scope of this application? I know that it's a lot of work to implement this, i've tried myself with an Electron application. I'd love to help out, but i only know web programming languages.

**Comment by Xen-E** [comment]
Hi there, This feature already exists... it's called "path prefix" in settings tab.
You can use it to fix broken file paths in playlists.

**Comment by FunctionDJ** [comment]
That's very neat, but not the feature i described, where the program keeps a database of existing files and suggests matches for missing tracks.

**Comment by Xen-E** [comment]
Hmm, That's very interesting...But it's hard to implement because the whole idea of this app is to read, manage, convert & create playlists.
Creating a "database" and keep watching it in the background while suggesting missing tracks using an algorithm will require to rewrite most of the code which is possible but is a lot of work and also defeats the purpose of this software.
BUT i can add an option to warn user of missing tracks, Like making tracks in the list different color, he then can fix it by "Path Prefix" feature or just by double clicking the column.
In general most people don't care about this stuff they just want a little simple tool to convert playlists so they go on with their life.

**Comment by Xen-E** [comment]
Alright, it took me about 20 minutes but i did implement something helpful, Here's an example:

Option
![missingfilestesting1](https://user-images.githubusercontent.com/22917711/123432929-d2169880-d5c2-11eb-8486-1aea7a6f85b1.PNG)

In action
![missingfilestesting2](https://user-images.githubusercontent.com/22917711/123433002-e65a9580-d5c2-11eb-84b3-daa37d9aa210.PNG)

This is the commit:
https://github.com/Xen-E/pcxx/commit/6691591900df64efec60f1e9c9fff44fe9f67e9b

Test it if you could and see if it works. That's all i can do for now. Take care.

**Comment by FunctionDJ** [comment]
Thank you very much, this is already very helpful ♥
